######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 30 01:55:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += webkit

# Input
HEADERS += mainwindow.h quiz.h ui_mainwindow.h
SOURCES += main.cpp mainwindow.cpp quiz.cpp
